apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: gateway
  name: gateway
  selfLink: /api/v1/namespaces/default/services/gateway
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32134
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: gateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
