apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mq
  name: mq
  selfLink: /api/v1/namespaces/default/services/mq
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    run: mq
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
